- name: deploy jupiter website
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: update ec2 instance
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: install apache server
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution != 'Ubuntu'

    - name: change directory to the html directory
      command: cd /var/www/html
      when: ansible_distribution != 'Ubuntu'

    - name: download web files from github
      get_url:
        url: https://github.com/azeezsalu/jupiter/archive/refs/heads/main.zip
        dest: /var/www/html/

    - name: Install unzip and tar packages
      yum:
        name:
          - unzip
          - tar
        state: present
      when: ansible_distribution != 'Ubuntu'

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/jupiter-main.zip
        dest: /var/www/html
        remote_src: yes
      when: ansible_distribution != 'Ubuntu'

    - name: copy webfiles from the jupiter-main directory to the html directory
      copy: 
        src: /var/www/html/jupiter-main/
        dest: /var/www/html
        remote_src: yes

    - name: remove the jupiter-main directory
      file: 
        path: /var/www/html/jupiter-main
        state: absent

    - name: remove the jupiter-main.zip folder
      file: 
        path: /var/www/html/jupiter-main.zip
        state: absent

    - name: start apache server, if not started
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started
      when: ansible_distribution != 'Ubuntu'
