---

- name: deploy techmax website
  hosts: all
  become: true
  #become_user: root

  tasks:
    - name: update ec2 instance
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install apache server
      yum:
        name: httpd
        state: latest
      when: ansible_distribution != 'Ubuntu'

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: change directory to the html directory
      command: cd /var/www/html
      when: ansible_distribution != 'Ubuntu'

    - name: change directory to the html directory
      shell: cd /var/www/html
      when: ansible_distribution == "Ubuntu"

    - name: download web files from github
      get_url:
        url: https://github.com/azeezsalu/techmax/archive/refs/heads/main.zip
        dest: /var/www/html/

    - name: Install unzip and tar packages
      yum:
        name:
          - unzip
          - tar
        state: present
      when: ansible_distribution != 'Ubuntu'

    - name: Install unzip and tar packages
      apt:
        name:
          - unzip
          - tar
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/techmax-main.zip
        dest: /var/www/html
        remote_src: yes

    - name: copy webfiles from the techmax-main directory to the html directory
      copy: 
        src: /var/www/html/techmax-main/
        dest: /var/www/html
        remote_src: yes

    - name: remove the techmax-main directory
      file: 
        path: /var/www/html/techmax-main
        state: absent

    - name: remove the techmax-main.zip folder
      file: 
        path: /var/www/html/techmax-main.zip
        state: absent 

    - name: start apache server, if not started
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started
      when: ansible_distribution != 'Ubuntu'

    - name: Start Apache2
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
