---

- hosts: all
  become: true
  tasks:

  - name: install updates (centos)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
    
 # - name: Enable service to start on boot up
  #  service:
   #   name: httpd
    #  state: started
   # when: ansible_distribution == "RedHat"


