---

- hosts: all
  become: true
  tasks:

  - name: install the apache and php packages for RedHat
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    
 # - name: Enable service to start on boot up
  #  service:
   #   name: httpd
    #  state: started
   # when: ansible_distribution == "RedHat"


