---

- hosts: all
  become: true
  tasks:

  - name: install the apache and php packages for RedHat
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"


