---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install the apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"


