---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    dnf:
      update_cache: yes

  - name: install the apache2 package
    dnf:
      name: httpd
      state: latest


  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started


