---
- name: Install Firefox package
  hosts: all
  become: true
  tasks:
    - name: Install Firefox package on Red Hat
      dnf:
        name: firefox
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

    - name: Log error for unsupported platforms
      debug:
        msg: "No valid platform. Exiting."
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
